# Generated by Django 5.1.5 on 2025-01-18 04:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('horario_preferencia', models.CharField(choices=[('Manhã', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Manhã', max_length=10, verbose_name='Horário de preferência')),
            ],
        ),
    ]
