# Generated by Django 5.1.5 on 2025-01-19 22:49

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='exemplo@exemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contato',
            name='nome',
            field=models.CharField(default='exemplo@exemplo.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='primeira_consulta',
            field=models.BooleanField(default=False, verbose_name='É sua primeira consulta?'),
        ),
        migrations.AddField(
            model_name='contato',
            name='tipo_consulta',
            field=models.CharField(choices=[('Avaliação Geral', 'Geral'), ('Emergencial', 'Emergencial'), ('Outros', 'Outros')], default='Avaliação Geral', max_length=15, verbose_name='Tipo de consulta'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
